name: Trigger auto deployment for backstage

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/backstage-AutoDeployTrigger-4e73bfe0-c20c-4acf-bdb5-4e1bb420a4b5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
        
      - name: Install dependancies
        run: yarn
        
      - name: Build backstage backend
        run: |
          yarn tsc
          yarn build:backend

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/datacom-frontend-development/fe-backstage:${{ github.sha }}
          file: packages/backend/Dockerfile
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BACKSTAGE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n backstage -g Mocatad_EV103_AE --server ghcr.io --username  ${{ secrets.BACKSTAGE_REGISTRY_USERNAME }} --password ${{ secrets.BACKSTAGE_REGISTRY_PASSWORD }}
            az containerapp update -n backstage -g Mocatad_EV103_AE --image ghcr.io/datacom-frontend-development/fe-backstage:${{ github.sha }}
